language: python
sudo: required
python:
    - "2.7"
services:
    - postgresql
    - redis
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
deploy:
    provider: pypi
    username: "$PYPI_USER"
    password: "$PYPI_PASSWORD"
    distributions: "sdist bdist_wheel"
    on:
        python: 2.7
        tags: true
        # branch: master
